### ISSUE TITLE
Make speed and jump force configurable

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#10]
## Planned outcome:
The movement speed of players and the jump height/force can be configured by adjusting the value of properties

## Tasks:
- [x] Add a serialized field `moveSpeed` to the PlayerController class
- [x] Add a serialized field `jumpForce` to the PlayerController class
- [x] Use these fields in `HandleMovement` and `Jump` methods

## Notes:

**Comment by DarioLoll** [comment]
Completed on the 16th of September 2023
