### ISSUE TITLE
Add kicking to Input Actions

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#11]
## Planned outcome:
A C# class that provides events and methods to read and process player input, now updated to listen for keys assigned to kicking

## Tasks:
- [x] #8 
- [x] Add the Action Kick in both maps: MovementRight and MovementLeft
- [x] Assign "Button" to the Action Type of both Kick actions
- [x] Assign the "R" key to the Binding under MovementLeft / Kick and "Down Arrow" to the Binding under MovementRight / Kick
- [x] Add another Binding to both Kick actions 
- [x] Assign the "S" key to the Binding under MovementLeft / Kick and "P" to the Binding under MovementRight / Kick

## Notes:

**Comment by DarioLoll** [comment]
Completed on the 18th of September 2023
