### ISSUE TITLE
Make the boot rotate when kicking

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#12]
## Planned outcome:
When holding down the R / S key, in the case of the left player, or P / Down arrow key in the case of the right player, the boot starts rotating around the player in the direction the player is facing (up to 90°), making it appear as if the player is kicking.

## Tasks:
- [x] Create an empty `GameObject` called BootPivot and make it a child of the Player in the Player prefab
- [x] Position the BootPivot at the center of the player's body 
- [x] Make the **Boot** object a child of the **BootPivot**
> [!NOTE]
> With this setup, whenever the boot is rotated, it will rotate around the player's center, not its center
- [x] Add a method to the PlayerController class called `HandleKicking` that is called in the `Update` method
- [x] Inside of `HandleKicking`, check whether the kick button is pressed at the moment
- [x] If yes: Rotate the boot by a small amount on the Z-Axis unless it has already reached 90°
- [x] If no: Rotate the boot by a negative number on the Z-Axis unless it has already reached 0°
> [!NOTE]
> To check if the boot has reached/gone below 0°, check if its rotation is above 180°

> [!IMPORTANT]
> Use the `Transform.localRotation.eulerAngles` property to check the rotation
## Notes:
Add a property `+bool IsKicking {get;}` to make the code more readable

**Comment by DarioLoll** [comment]
Completed on the 18th of September 2023
