### ISSUE TITLE
Add force to the ball when kicked

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#13]
## Planned outcome:
If a player's boot touches the ball, a force should be applied to the ball in the appropriate directon, making it appear as if the ball was kicked.

## Tasks:
- [x] Create a new Script and attach it to the **Boot** object in the Player prefab
- [x] In the `OnCollisionEnter2D` method of this script, check if the `collision` is the Ball and if the player is kicking
- [x] Calculate the direction in which the ball should be kicked
- [x] Add an impulse force to the ball in the calculated direction

## Notes:

**Comment by DarioLoll** [comment]
Completed on the 18th of September 2023
