### ISSUE TITLE
Create a Main Menu scene

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#14]
## Planned outcome:
A scene with a background image, a title and three buttons: Offline, Online, and Quit

## Tasks:
- [x] Create a scene called **MainMenu**
- [x] Create a UI Element of the type Canvas called **CanvasMain**
- [x] Add a UI Element of the type Image for the background Image
- [x] Add a TextMeshPro UI Element for the title
- [x] Add three Button UI Elements
- [x] Resize, Position and Customize the UI Elements appropriately
- [x] Create a `MainMenuVM` script that handles user input for the main menu scene
- [x] Implement a `StartOfflineGame` method that is called when the **Offline** button is pressed. This method simply switches to the Match scene.
- [x] Implement a `Quit` method that is called when the **Quit** button is pressed. This method simply closes the application.

## Notes:

**Comment by DarioLoll** [comment]
Completed on the 18th of September 2023
