### ISSUE TITLE
Add a screen for starting an online game

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#15]
## Planned outcome:
A screen pops up when the user selects the online mode in the main menu. This screen lets the player choose between joining a lobby by code, joining a random lobby, or creating their own lobby.

## Tasks:
- [x] Add a Canvas UI Element **CanvasOnline** to the Main Menu scene
- [x] Add a TextMeshPro UI Element for the Title of the screen
- [x] Add four buttons to **CanvasOnline**: `Quick Join`, `Create Lobby`, `Join by Code` and `Back`
- [x] Add an Input Field UI Element next to the `Join by Code` button
- [x] Resize, Position and Customize the elements appropriately
- [x] Disable the **CanvasOnline** to by default
- [x] Implement a method `StartOnlineGame` in `MainMenuVM` that sets **CanvasOnline** to active
- [x] Implement a method `BackToMainMenu` in `MainMenuVM` that disables the **CanvasOnline**

## Notes:

**Comment by DarioLoll** [comment]
Completed on the 18th of September 2023
