### ISSUE TITLE
Add a screen for creating a lobby

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#16]
## Planned outcome:
A screen pops up when the user chooses to create a lobby in the main menu. This screen lets the player choose whether the lobby will be public or private, and what the name of the lobby will be.

## Tasks:
- [x] Add a Canvas UI Element **CanvasLobby** to the Main Menu scene
- [x] Add a TextMeshPro UI Element for the Title of the screen
- [x] Add an Input Field UI Element for entering the name of the lobby 
- [x] Add three buttons to **CanvasOnline**: `Create public`, `Create private` and `Back`
- [x] Resize, Position and Customize the elements appropriately
- [x] Disable the **CanvasLobby** by default
- [x] Implement a method `CreateLobby` in `MainMenuVM` that enables the **CanvasLobby** and disables the **CanvasOnline**
- [x] Implement a method `BackToCanvasOnline` in `MainMenuVM` that disables the **CanvasLobby** and enables the **CanvasOnline**

## Notes:

**Comment by DarioLoll** [comment]
Completed on the 25th Of September
