### ISSUE TITLE
Create the Lobby scene

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#17]
## Planned outcome:
When a user creates or joins a lobby, they should enter the lobby scene where they can say that they're ready to start the match, leave the lobby, see the name and the code of the lobby and kick players if they are the lobby owner.

## Tasks:
- [x] Create a scene in unity called **Lobby**
- [x] Add a background image
- [x] Add a TextMeshPro UI Element for the Title of the screen
- [x] Add a TextMeshPro UI Element for the Name of the lobby
- [x] Add two TextMeshPro UI Elements for the names of the players
- [x] Add two TextMeshPro UI Elements for displaying whether players are ready or not
- [x] Add a Button UI Element for leaving the lobby
- [x] Add a Button UI Element for changing the ready status
- [x] Add a read-only input field UI Element for displaying the code of the lobby
- [x] Resize, Position and Customize the elements appropriately

## Notes:

**Comment by DarioLoll** [comment]
Completed on the 28th of September 2023
