### ISSUE TITLE
Implement the logic for creating lobbies

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#18]
## Planned outcome:
When the user clicks on the "Create Lobby" button in the main menu, a lobby is created and the lobby scene pops up with all of the placeholders in the scene populated.

## Tasks:
- [x] Create a `LobbyManager` script
- [x] Create an empty GameObject in the MainMenu scene
- [x] Attach the `LobbyManager` script to the empty GameObject
- [x] Add a reference to the LobbyManager pointing to the Input Field where the user enters the lobby name
- [x] Implement a method `CreateLobby` in the `LobbyManager` and call it when the user clicks on the corresponding button
- [x] Implement a method in the `LobbyManager` that pings all the lobbies from time to time in order to keep them active
- [x] Switch to the Lobby scene when the lobby is created

## Notes:

**Comment by DarioLoll** [comment]
In order for a lobby to be created by a player, the player needs to be signed in.
- [ ] #20

**Comment by DarioLoll** [comment]
- [ ] Create and pass in player data of the host in the CreateLobbyOptions parameter
