### ISSUE TITLE
Lobby scene management

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#19]
## Planned outcome:
The placeholders in the lobby scene: Lobby name, Lobby code, Player names, and player's ready status are correctly synced for the players in the lobby. The host can kick the other player, both players can leave the lobby when they want. If the host leaves, the other player becomes the host. The host can't start the game until the other player is ready.

## Tasks:
- [x] #18 
- [x] Store the lobby the player is currently in
- [x] Update the stored lobby when a player creates, joins or leaves a lobby
- [x] Poll for updates for the lobby the player is in every 1.1 seconds (GetLobbyAsync method)
- [x] Update placeholders in the lobby scene
- [x] Give the host the ability to kick the other player
- [x] Give the host the ability to change the properties of the lobby (name, public/private...)
- [x] Switch to main menu when the player leaves or is kicked from the lobby
- [x] Pass in a bool as player data that stores whether the player is ready or not
- [x] Update player data when the ready status changes
- [x] Make sure that the other player becomes the host when the original host leaves the lobby
- [x] Start the game when the host clicks on start and the other player is there and ready
- [x] Make sure that the LobbyManager always has references to needed input fields in the main menu (after a player leaves a lobby, and is back in the main menu, they should still be able to join or create another lobby)
- [x] Document the code

## Notes:
https://www.youtube.com/watch?v=-KDlEBfCBiU
