### ISSUE TITLE
Unity Authentication

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#20]
## Planned outcome:
Players need to be authenticated in order to use unity gaming services such as lobbies. When they are authenticated, they are assigned a UUID.

## Tasks:
- [x] Read [the documentation on Unity Authentication](https://docs.unity.com/ugs/manual/authentication/manual/overview)
- [x] Make sure to initialize UnitySevices before using them
- [x] Add a window before the main menu
- [x] In this window, add an input field for the player's name
- [x] Add a button to the window that signs in the player when clicked
- [x] Sign in the player anonymously and set the given name
- [x] Catch exceptions and display them to the player appropriately

## Notes:
