### ISSUE TITLE
Implement the logic for joining lobbies

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#21]
## Planned outcome:
Players can join a lobby by entering its code or by selecting quick join, which will put them into a random public lobby.

## Tasks:
- [x] #18 
- [x] #20 
- [x] Read the code from the input field
- [x] Implement joining by code
- [x] Implement quick join
- [x] Create and pass in player data as a part of the join call
- [x] Catch exceptions

## Notes:
The implementation hasn't been planned out yet
Sources for learning:
https://docs.unity.com/ugs/en-us/manual/lobby/manual/manage-lobbies
https://youtu.be/-KDlEBfCBiU?si=3DmbINyBEWqw4cI2
