### ISSUE TITLE
Automate test issue creation

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#24]
## Planned outcome:
For every issue created, GitHub should automatically create another issue titled "Test <name of the issue>"

## Tasks:
- [ ] Create a GitHub workflow file
- [ ] Define a new workflow
- [ ] Define steps (what should GitHub do)
- [ ] Commit the workflow file
