### ISSUE TITLE
Create a prototype for the soccer field

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#3]
## Planned outcome:
A 2D rectangle in the **Match Scene**, with alternating green and dark green stripes representing the grass. 

## Tasks:
- [x] Create an empty `GameObject` with the name _**Field**_
- [x] Add a 2D Sprite of the type Rectangle into the Match Scene
- [x] Make the rectangle a child of the _**Field**_ `GameObject`
- [x] Position the Rectangle appropriately 
- [x] Make the Rectangle green
- [x] Add dark green stripes by creating multiple rectangles and laying them over the base rectangle
- [x] Add a `2D Box Collider` component to the **Field** `GameObject`
- [x] Resize and position the 2D Box Collider so it matches the width and height of the field
- [x] Cut off the upper half of the Box Collider so that the players and the ball would stand in the middle of the field

**Comment by DarioLoll** [comment]
> [!NOTE]
> Completed on the 16.9.2023
