### ISSUE TITLE
Display lobby exceptions in the UI

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#31]
## Planned outcome:
Display errors in the UI when lobbies don't work, when the player is kicked from the lobbie, etc.
The user should always know what is happening and why something isn't working

## Tasks:
- [x] Design an error pop-up window
- [x] Make the error pop-up window a prefab
- [x] Write a script that provides access for other classes to edit the prefab (most importantly the error message)
- [x] Figure out how to find out what error occured when exactly (Did the attempt to join a lobby fail because the user isn't connected to the network or because a lobby with the provided code doesn't exist?)
- [x] Display errors at logging in: Invalid name / No network connection / unexpected error
- [x] Display errors at joining lobby with code: No network connection / No lobby found / Unexpected error
- [x] Display errors at quick joining: No network connection / No lobby found / Unexpected error
- [x] Display errors at creating a lobby: No network connection / Invalid name / Unexpected error
