### ISSUE TITLE
Make the player color configurable

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#34]
## Planned outcome:
The only thing that differentiates the players now are their names. The host in the lobby is always red while the other player is always blue which doesn't make sense because when the original host leaves, the blue player suddenly becomes red. All players should have and be able to retain and choose their own color. 

## Tasks:
- [x] Add a property to the player prefab that provides access to the color of the body
- [x] Figure out how to have the user pick a color in an easy and understandable way
- [x] Figure out how the color can be stored as a string
- [x] When creating a player object to pass to the lobby, add a color property and assign it a random color
- [x] Update the player data when the user changes the color of their player, so that the [5 requests in 5 seconds limit](https://docs.unity.com/ugs/en-us/manual/lobby/manual/rate-limits) isn't gone over
