### ISSUE TITLE
Create Goal prototype

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#4]
## Planned outcome:
Two 2D white rectangles in the **Match Scene**, on each end of the soccer field, representing the post and the crossbar of a goal.

## Tasks:
- [x] Create an empty `GameObject` with the name **LeftGoal**
- [x] Add a 2D Sprite of the type Rectangle into the Match Scene
- [x] Make the rectangle a child of the **LeftGoal** `GameObject`
- [x] Position and resize the Rectangle so that it looks like a goal post
- [x] Repeat the process in order to make a crossbar for the goal
- [x] Add a `2D Box Collider` to the **Crossbar** `GameObject`
- [x] Duplicate the **LeftGoal** `GameObject`, name it **RightGoal**, make the scale on the X-Axis `-1` and position it appropriately

## Notes:
 Since there are two goals that should always remain the same, apart from one being flipped on the X-Axis, making the goal GameObject a prototype might also be a good idea.

**Comment by DarioLoll** [comment]
> [!NOTE]
> Completed on the 16.09.2023

**Comment by DarioLoll** [comment]
Completed on the 16th of September 2023.
