### ISSUE TITLE
Create a prototype for a soccer ball

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#5]
## Planned outcome:
A 2D Circle Sprite in the **Match Scene** that is affected by physics (gravity)

## Tasks:
- [x] Create an empty `GameObject` with the name **Ball**
- [x] Add a 2D Sprite of the type Circle into the Match Scene
- [x] Make the circle a child of the **Ball** `GameObject`
- [x] Position and resize the Ball appropriately
- [x] Add a `2D Circle Collider` to the **Ball** `GameObject`
- [x] Add a `RigidBody2D` component to the **Ball** to make it be affected by physics 

## Notes:

**Comment by DarioLoll** [comment]
Completed on the 16th of September 2023

**Comment by DarioLoll** [comment]
Completed on the 16th of September 2023
