### ISSUE TITLE
Add Walls to the Match Scene Prototype

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#6]
## Planned outcome:
Make sure the ball and the players can't go/fly out of the scene

## Tasks:
- [x] Create three empty `GameObject`s with names **LeftWall**, **TopWall** and **RightWall**
- [x] Place the GameObjects on their respective sides of the scene
- [x] Add a `2D Box Collider` component to each GameObject
- [x] Resize the colliders appropriately

## Notes:

**Comment by DarioLoll** [comment]
Completed on the 16th of September 2023
