### ISSUE TITLE
Create a Prototype for a player

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#7]
## Planned outcome:
A 2D sprite consisting of a head and a foot that is affected by physics (gravity etc.)

## Tasks:
- [x] Create an empty `GameObject` with the name **Player** and drag it into the Project tab to make it a Prefab
- [x] Add a 2D Sprite of the type Circle into the Match Scene called **Body**
- [x] Make the circle a child of the **Player** `GameObject`
- [x] Add a 2D Closed sprite shape to the **Player** object and name it **Boot**
- [x] Make the shape look like a foot, resize it and position it under the body.
- [x] Add a 2D Circle collider to the **Player** object
- [x] Add a 2D Polygon collider to the **Boot** object and resize it appropriately
- [x] Add two instances of the player prefab into the Match scene, position and resize them appropriately

## Notes:

**Comment by DarioLoll** [comment]
Completed on the 16th of September 2023
