### ISSUE TITLE
Create Input Actions

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#8]
## Planned outcome:
A C# class that provides events and methods to read and process player input

## Tasks:
- [x] Install the new Input System Package in Unity
- [x] Create an "Input Actions" object in the Project tab
- [x] Create two Action Maps: MovementRight and MovementLeft
- [x] Create two Actions in both maps: Move and Jump
- [x] Assign "Value" to the Action Type of both Move actions and "Axis" to the Control type
- [x] Assign "Button" to the Action Type of both Jump actions
- [x] Assign the "W" key to the Binding under MovementLeft / Jump and "Up Arrow" to the Bindign under MovementRight / Jump
- [x] Create a "Positive/Negative Binding" under both Move actions
- [x] Assign the "A" key to the negative binding under MovementLeft / Move / 1D Axis, and the "D" key to the positive binding
- [x] Assign the "Left Arrow" key to the negative binding under MovementRight / Move / 1D Axis, and the "Right Arrow" key to the positive binding  
- [x] Generate the C# class for the input actions object 

## Notes:

**Comment by DarioLoll** [comment]
Completed on the 16th of September 2023
