### ISSUE TITLE
Implement player movement

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/SoccerHeads#9]
## Planned outcome:
The two players in the Match Scene move after certain keys on the keyboard are pressed
Moving on the X axis:
 - Move left: A Key / Left arrow Key
 - Move right: D Key / Right arrow Key
Moving on the Y axis:
 - Jumping: W Key / Up arrow key
Player on the left moves with W/A/D
Player on the right moves with arrow keys

## Tasks:
- [x] #8 
- [x] Create a PlayerController script and add it to the Player prefab
- [x] Implement a `HandleMovement` method that is called every frame in the `FixedUpdate` method. 
> [!NOTE]
> In this method, read the input by accessing the `InputActions` class, calculate and apply some velocity to the `RigidBody2D` component of the player

> [!NOTE]
> Check if the player's scale on the X-Axis is 1 or -1 in order to know which action map (MovementRight/Left) to read from.
- [x] Implement the jumping logic by having a boolean field that stores whether the player is currently on the ground or not, and a method `Jump` that is called when the Jump action in the `InputActions` class is performed (subscribe to the event)
> [!NOTE]
> Set the boolean field to true in the `OnCollisionEnter2D` method if what the player collided with is the ground

## Notes:
This script will certainly need to be updated in the future.

**Comment by DarioLoll** [comment]
Completed on the 16th of September 2023
